// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query4.proto

package edu_cost_stat;

public final class Query4 {
  private Query4() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryFourRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu_cost_stat.QueryFourRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 years = 1;</code>
     * @return A list containing the years.
     */
    java.util.List<java.lang.Integer> getYearsList();
    /**
     * <code>repeated int32 years = 1;</code>
     * @return The count of years.
     */
    int getYearsCount();
    /**
     * <code>repeated int32 years = 1;</code>
     * @param index The index of the element to return.
     * @return The years at the given index.
     */
    int getYears(int index);

    /**
     * <code>int32 year = 2;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string length = 4;</code>
     * @return The length.
     */
    java.lang.String getLength();
    /**
     * <code>string length = 4;</code>
     * @return The bytes for length.
     */
    com.google.protobuf.ByteString
        getLengthBytes();
  }
  /**
   * Protobuf type {@code edu_cost_stat.QueryFourRequest}
   */
  public static final class QueryFourRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu_cost_stat.QueryFourRequest)
      QueryFourRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryFourRequest.newBuilder() to construct.
    private QueryFourRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryFourRequest() {
      years_ = emptyIntList();
      type_ = "";
      length_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryFourRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu_cost_stat.Query4.QueryFourRequest.class, edu_cost_stat.Query4.QueryFourRequest.Builder.class);
    }

    public static final int YEARS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList years_;
    /**
     * <code>repeated int32 years = 1;</code>
     * @return A list containing the years.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getYearsList() {
      return years_;
    }
    /**
     * <code>repeated int32 years = 1;</code>
     * @return The count of years.
     */
    public int getYearsCount() {
      return years_.size();
    }
    /**
     * <code>repeated int32 years = 1;</code>
     * @param index The index of the element to return.
     * @return The years at the given index.
     */
    public int getYears(int index) {
      return years_.getInt(index);
    }
    private int yearsMemoizedSerializedSize = -1;

    public static final int YEAR_FIELD_NUMBER = 2;
    private int year_ = 0;
    /**
     * <code>int32 year = 2;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object length_ = "";
    /**
     * <code>string length = 4;</code>
     * @return The length.
     */
    @java.lang.Override
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <code>string length = 4;</code>
     * @return The bytes for length.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getYearsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(yearsMemoizedSerializedSize);
      }
      for (int i = 0; i < years_.size(); i++) {
        output.writeInt32NoTag(years_.getInt(i));
      }
      if (year_ != 0) {
        output.writeInt32(2, year_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(length_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, length_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < years_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(years_.getInt(i));
        }
        size += dataSize;
        if (!getYearsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        yearsMemoizedSerializedSize = dataSize;
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, year_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(length_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu_cost_stat.Query4.QueryFourRequest)) {
        return super.equals(obj);
      }
      edu_cost_stat.Query4.QueryFourRequest other = (edu_cost_stat.Query4.QueryFourRequest) obj;

      if (!getYearsList()
          .equals(other.getYearsList())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getLength()
          .equals(other.getLength())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getYearsCount() > 0) {
        hash = (37 * hash) + YEARS_FIELD_NUMBER;
        hash = (53 * hash) + getYearsList().hashCode();
      }
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query4.QueryFourRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu_cost_stat.Query4.QueryFourRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu_cost_stat.QueryFourRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu_cost_stat.QueryFourRequest)
        edu_cost_stat.Query4.QueryFourRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu_cost_stat.Query4.QueryFourRequest.class, edu_cost_stat.Query4.QueryFourRequest.Builder.class);
      }

      // Construct using edu_cost_stat.Query4.QueryFourRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        years_ = emptyIntList();
        year_ = 0;
        type_ = "";
        length_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourRequest_descriptor;
      }

      @java.lang.Override
      public edu_cost_stat.Query4.QueryFourRequest getDefaultInstanceForType() {
        return edu_cost_stat.Query4.QueryFourRequest.getDefaultInstance();
      }

      @java.lang.Override
      public edu_cost_stat.Query4.QueryFourRequest build() {
        edu_cost_stat.Query4.QueryFourRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu_cost_stat.Query4.QueryFourRequest buildPartial() {
        edu_cost_stat.Query4.QueryFourRequest result = new edu_cost_stat.Query4.QueryFourRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(edu_cost_stat.Query4.QueryFourRequest result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          years_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.years_ = years_;
      }

      private void buildPartial0(edu_cost_stat.Query4.QueryFourRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.year_ = year_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.length_ = length_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu_cost_stat.Query4.QueryFourRequest) {
          return mergeFrom((edu_cost_stat.Query4.QueryFourRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu_cost_stat.Query4.QueryFourRequest other) {
        if (other == edu_cost_stat.Query4.QueryFourRequest.getDefaultInstance()) return this;
        if (!other.years_.isEmpty()) {
          if (years_.isEmpty()) {
            years_ = other.years_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureYearsIsMutable();
            years_.addAll(other.years_);
          }
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureYearsIsMutable();
                years_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureYearsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  years_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 16: {
                year_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                length_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList years_ = emptyIntList();
      private void ensureYearsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          years_ = mutableCopy(years_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated int32 years = 1;</code>
       * @return A list containing the years.
       */
      public java.util.List<java.lang.Integer>
          getYearsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(years_) : years_;
      }
      /**
       * <code>repeated int32 years = 1;</code>
       * @return The count of years.
       */
      public int getYearsCount() {
        return years_.size();
      }
      /**
       * <code>repeated int32 years = 1;</code>
       * @param index The index of the element to return.
       * @return The years at the given index.
       */
      public int getYears(int index) {
        return years_.getInt(index);
      }
      /**
       * <code>repeated int32 years = 1;</code>
       * @param index The index to set the value at.
       * @param value The years to set.
       * @return This builder for chaining.
       */
      public Builder setYears(
          int index, int value) {

        ensureYearsIsMutable();
        years_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 years = 1;</code>
       * @param value The years to add.
       * @return This builder for chaining.
       */
      public Builder addYears(int value) {

        ensureYearsIsMutable();
        years_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 years = 1;</code>
       * @param values The years to add.
       * @return This builder for chaining.
       */
      public Builder addAllYears(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureYearsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, years_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 years = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearYears() {
        years_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 2;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 2;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {

        year_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000002);
        year_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 3;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>string length = 4;</code>
       * @return The length.
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string length = 4;</code>
       * @return The bytes for length.
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string length = 4;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        length_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string length = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        length_ = getDefaultInstance().getLength();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string length = 4;</code>
       * @param value The bytes for length to set.
       * @return This builder for chaining.
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        length_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu_cost_stat.QueryFourRequest)
    }

    // @@protoc_insertion_point(class_scope:edu_cost_stat.QueryFourRequest)
    private static final edu_cost_stat.Query4.QueryFourRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu_cost_stat.Query4.QueryFourRequest();
    }

    public static edu_cost_stat.Query4.QueryFourRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryFourRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryFourRequest>() {
      @java.lang.Override
      public QueryFourRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QueryFourRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryFourRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu_cost_stat.Query4.QueryFourRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryFourResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu_cost_stat.QueryFourResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    java.util.List<edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair> 
        getStateGrowthPairsList();
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair getStateGrowthPairs(int index);
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    int getStateGrowthPairsCount();
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    java.util.List<? extends edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder> 
        getStateGrowthPairsOrBuilderList();
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder getStateGrowthPairsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code edu_cost_stat.QueryFourResponse}
   */
  public static final class QueryFourResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu_cost_stat.QueryFourResponse)
      QueryFourResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryFourResponse.newBuilder() to construct.
    private QueryFourResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryFourResponse() {
      stateGrowthPairs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryFourResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu_cost_stat.Query4.QueryFourResponse.class, edu_cost_stat.Query4.QueryFourResponse.Builder.class);
    }

    public interface StateGrowthPairOrBuilder extends
        // @@protoc_insertion_point(interface_extends:edu_cost_stat.QueryFourResponse.StateGrowthPair)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string state = 1;</code>
       * @return The state.
       */
      java.lang.String getState();
      /**
       * <code>string state = 1;</code>
       * @return The bytes for state.
       */
      com.google.protobuf.ByteString
          getStateBytes();

      /**
       * <code>double growth_rate = 2;</code>
       * @return The growthRate.
       */
      double getGrowthRate();
    }
    /**
     * Protobuf type {@code edu_cost_stat.QueryFourResponse.StateGrowthPair}
     */
    public static final class StateGrowthPair extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:edu_cost_stat.QueryFourResponse.StateGrowthPair)
        StateGrowthPairOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use StateGrowthPair.newBuilder() to construct.
      private StateGrowthPair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private StateGrowthPair() {
        state_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new StateGrowthPair();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.class, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder.class);
      }

      public static final int STATE_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object state_ = "";
      /**
       * <code>string state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        }
      }
      /**
       * <code>string state = 1;</code>
       * @return The bytes for state.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int GROWTH_RATE_FIELD_NUMBER = 2;
      private double growthRate_ = 0D;
      /**
       * <code>double growth_rate = 2;</code>
       * @return The growthRate.
       */
      @java.lang.Override
      public double getGrowthRate() {
        return growthRate_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, state_);
        }
        if (java.lang.Double.doubleToRawLongBits(growthRate_) != 0) {
          output.writeDouble(2, growthRate_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, state_);
        }
        if (java.lang.Double.doubleToRawLongBits(growthRate_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, growthRate_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair)) {
          return super.equals(obj);
        }
        edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair other = (edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair) obj;

        if (!getState()
            .equals(other.getState())) return false;
        if (java.lang.Double.doubleToLongBits(getGrowthRate())
            != java.lang.Double.doubleToLongBits(
                other.getGrowthRate())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
        hash = (37 * hash) + GROWTH_RATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getGrowthRate()));
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code edu_cost_stat.QueryFourResponse.StateGrowthPair}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:edu_cost_stat.QueryFourResponse.StateGrowthPair)
          edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.class, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder.class);
        }

        // Construct using edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          state_ = "";
          growthRate_ = 0D;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_descriptor;
        }

        @java.lang.Override
        public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair getDefaultInstanceForType() {
          return edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.getDefaultInstance();
        }

        @java.lang.Override
        public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair build() {
          edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair buildPartial() {
          edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair result = new edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.state_ = state_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.growthRate_ = growthRate_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair) {
            return mergeFrom((edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair other) {
          if (other == edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.getDefaultInstance()) return this;
          if (!other.getState().isEmpty()) {
            state_ = other.state_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.getGrowthRate() != 0D) {
            setGrowthRate(other.getGrowthRate());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  state_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 17: {
                  growthRate_ = input.readDouble();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 17
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object state_ = "";
        /**
         * <code>string state = 1;</code>
         * @return The state.
         */
        public java.lang.String getState() {
          java.lang.Object ref = state_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            state_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string state = 1;</code>
         * @return The bytes for state.
         */
        public com.google.protobuf.ByteString
            getStateBytes() {
          java.lang.Object ref = state_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            state_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string state = 1;</code>
         * @param value The state to set.
         * @return This builder for chaining.
         */
        public Builder setState(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          state_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string state = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearState() {
          state_ = getDefaultInstance().getState();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string state = 1;</code>
         * @param value The bytes for state to set.
         * @return This builder for chaining.
         */
        public Builder setStateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          state_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private double growthRate_ ;
        /**
         * <code>double growth_rate = 2;</code>
         * @return The growthRate.
         */
        @java.lang.Override
        public double getGrowthRate() {
          return growthRate_;
        }
        /**
         * <code>double growth_rate = 2;</code>
         * @param value The growthRate to set.
         * @return This builder for chaining.
         */
        public Builder setGrowthRate(double value) {

          growthRate_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>double growth_rate = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearGrowthRate() {
          bitField0_ = (bitField0_ & ~0x00000002);
          growthRate_ = 0D;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:edu_cost_stat.QueryFourResponse.StateGrowthPair)
      }

      // @@protoc_insertion_point(class_scope:edu_cost_stat.QueryFourResponse.StateGrowthPair)
      private static final edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair();
      }

      public static edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<StateGrowthPair>
          PARSER = new com.google.protobuf.AbstractParser<StateGrowthPair>() {
        @java.lang.Override
        public StateGrowthPair parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<StateGrowthPair> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<StateGrowthPair> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int STATE_GROWTH_PAIRS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair> stateGrowthPairs_;
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair> getStateGrowthPairsList() {
      return stateGrowthPairs_;
    }
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder> 
        getStateGrowthPairsOrBuilderList() {
      return stateGrowthPairs_;
    }
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    @java.lang.Override
    public int getStateGrowthPairsCount() {
      return stateGrowthPairs_.size();
    }
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    @java.lang.Override
    public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair getStateGrowthPairs(int index) {
      return stateGrowthPairs_.get(index);
    }
    /**
     * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
     */
    @java.lang.Override
    public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder getStateGrowthPairsOrBuilder(
        int index) {
      return stateGrowthPairs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < stateGrowthPairs_.size(); i++) {
        output.writeMessage(1, stateGrowthPairs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < stateGrowthPairs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stateGrowthPairs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu_cost_stat.Query4.QueryFourResponse)) {
        return super.equals(obj);
      }
      edu_cost_stat.Query4.QueryFourResponse other = (edu_cost_stat.Query4.QueryFourResponse) obj;

      if (!getStateGrowthPairsList()
          .equals(other.getStateGrowthPairsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStateGrowthPairsCount() > 0) {
        hash = (37 * hash) + STATE_GROWTH_PAIRS_FIELD_NUMBER;
        hash = (53 * hash) + getStateGrowthPairsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query4.QueryFourResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu_cost_stat.Query4.QueryFourResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu_cost_stat.QueryFourResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu_cost_stat.QueryFourResponse)
        edu_cost_stat.Query4.QueryFourResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu_cost_stat.Query4.QueryFourResponse.class, edu_cost_stat.Query4.QueryFourResponse.Builder.class);
      }

      // Construct using edu_cost_stat.Query4.QueryFourResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (stateGrowthPairsBuilder_ == null) {
          stateGrowthPairs_ = java.util.Collections.emptyList();
        } else {
          stateGrowthPairs_ = null;
          stateGrowthPairsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu_cost_stat.Query4.internal_static_edu_cost_stat_QueryFourResponse_descriptor;
      }

      @java.lang.Override
      public edu_cost_stat.Query4.QueryFourResponse getDefaultInstanceForType() {
        return edu_cost_stat.Query4.QueryFourResponse.getDefaultInstance();
      }

      @java.lang.Override
      public edu_cost_stat.Query4.QueryFourResponse build() {
        edu_cost_stat.Query4.QueryFourResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu_cost_stat.Query4.QueryFourResponse buildPartial() {
        edu_cost_stat.Query4.QueryFourResponse result = new edu_cost_stat.Query4.QueryFourResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(edu_cost_stat.Query4.QueryFourResponse result) {
        if (stateGrowthPairsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            stateGrowthPairs_ = java.util.Collections.unmodifiableList(stateGrowthPairs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stateGrowthPairs_ = stateGrowthPairs_;
        } else {
          result.stateGrowthPairs_ = stateGrowthPairsBuilder_.build();
        }
      }

      private void buildPartial0(edu_cost_stat.Query4.QueryFourResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu_cost_stat.Query4.QueryFourResponse) {
          return mergeFrom((edu_cost_stat.Query4.QueryFourResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu_cost_stat.Query4.QueryFourResponse other) {
        if (other == edu_cost_stat.Query4.QueryFourResponse.getDefaultInstance()) return this;
        if (stateGrowthPairsBuilder_ == null) {
          if (!other.stateGrowthPairs_.isEmpty()) {
            if (stateGrowthPairs_.isEmpty()) {
              stateGrowthPairs_ = other.stateGrowthPairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStateGrowthPairsIsMutable();
              stateGrowthPairs_.addAll(other.stateGrowthPairs_);
            }
            onChanged();
          }
        } else {
          if (!other.stateGrowthPairs_.isEmpty()) {
            if (stateGrowthPairsBuilder_.isEmpty()) {
              stateGrowthPairsBuilder_.dispose();
              stateGrowthPairsBuilder_ = null;
              stateGrowthPairs_ = other.stateGrowthPairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stateGrowthPairsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStateGrowthPairsFieldBuilder() : null;
            } else {
              stateGrowthPairsBuilder_.addAllMessages(other.stateGrowthPairs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair m =
                    input.readMessage(
                        edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.parser(),
                        extensionRegistry);
                if (stateGrowthPairsBuilder_ == null) {
                  ensureStateGrowthPairsIsMutable();
                  stateGrowthPairs_.add(m);
                } else {
                  stateGrowthPairsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair> stateGrowthPairs_ =
        java.util.Collections.emptyList();
      private void ensureStateGrowthPairsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          stateGrowthPairs_ = new java.util.ArrayList<edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair>(stateGrowthPairs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder> stateGrowthPairsBuilder_;

      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public java.util.List<edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair> getStateGrowthPairsList() {
        if (stateGrowthPairsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stateGrowthPairs_);
        } else {
          return stateGrowthPairsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public int getStateGrowthPairsCount() {
        if (stateGrowthPairsBuilder_ == null) {
          return stateGrowthPairs_.size();
        } else {
          return stateGrowthPairsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair getStateGrowthPairs(int index) {
        if (stateGrowthPairsBuilder_ == null) {
          return stateGrowthPairs_.get(index);
        } else {
          return stateGrowthPairsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder setStateGrowthPairs(
          int index, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair value) {
        if (stateGrowthPairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStateGrowthPairsIsMutable();
          stateGrowthPairs_.set(index, value);
          onChanged();
        } else {
          stateGrowthPairsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder setStateGrowthPairs(
          int index, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder builderForValue) {
        if (stateGrowthPairsBuilder_ == null) {
          ensureStateGrowthPairsIsMutable();
          stateGrowthPairs_.set(index, builderForValue.build());
          onChanged();
        } else {
          stateGrowthPairsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder addStateGrowthPairs(edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair value) {
        if (stateGrowthPairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStateGrowthPairsIsMutable();
          stateGrowthPairs_.add(value);
          onChanged();
        } else {
          stateGrowthPairsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder addStateGrowthPairs(
          int index, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair value) {
        if (stateGrowthPairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStateGrowthPairsIsMutable();
          stateGrowthPairs_.add(index, value);
          onChanged();
        } else {
          stateGrowthPairsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder addStateGrowthPairs(
          edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder builderForValue) {
        if (stateGrowthPairsBuilder_ == null) {
          ensureStateGrowthPairsIsMutable();
          stateGrowthPairs_.add(builderForValue.build());
          onChanged();
        } else {
          stateGrowthPairsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder addStateGrowthPairs(
          int index, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder builderForValue) {
        if (stateGrowthPairsBuilder_ == null) {
          ensureStateGrowthPairsIsMutable();
          stateGrowthPairs_.add(index, builderForValue.build());
          onChanged();
        } else {
          stateGrowthPairsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder addAllStateGrowthPairs(
          java.lang.Iterable<? extends edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair> values) {
        if (stateGrowthPairsBuilder_ == null) {
          ensureStateGrowthPairsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, stateGrowthPairs_);
          onChanged();
        } else {
          stateGrowthPairsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder clearStateGrowthPairs() {
        if (stateGrowthPairsBuilder_ == null) {
          stateGrowthPairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stateGrowthPairsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public Builder removeStateGrowthPairs(int index) {
        if (stateGrowthPairsBuilder_ == null) {
          ensureStateGrowthPairsIsMutable();
          stateGrowthPairs_.remove(index);
          onChanged();
        } else {
          stateGrowthPairsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder getStateGrowthPairsBuilder(
          int index) {
        return getStateGrowthPairsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder getStateGrowthPairsOrBuilder(
          int index) {
        if (stateGrowthPairsBuilder_ == null) {
          return stateGrowthPairs_.get(index);  } else {
          return stateGrowthPairsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public java.util.List<? extends edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder> 
           getStateGrowthPairsOrBuilderList() {
        if (stateGrowthPairsBuilder_ != null) {
          return stateGrowthPairsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stateGrowthPairs_);
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder addStateGrowthPairsBuilder() {
        return getStateGrowthPairsFieldBuilder().addBuilder(
            edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.getDefaultInstance());
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder addStateGrowthPairsBuilder(
          int index) {
        return getStateGrowthPairsFieldBuilder().addBuilder(
            index, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.getDefaultInstance());
      }
      /**
       * <code>repeated .edu_cost_stat.QueryFourResponse.StateGrowthPair state_growth_pairs = 1;</code>
       */
      public java.util.List<edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder> 
           getStateGrowthPairsBuilderList() {
        return getStateGrowthPairsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder> 
          getStateGrowthPairsFieldBuilder() {
        if (stateGrowthPairsBuilder_ == null) {
          stateGrowthPairsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPair.Builder, edu_cost_stat.Query4.QueryFourResponse.StateGrowthPairOrBuilder>(
                  stateGrowthPairs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          stateGrowthPairs_ = null;
        }
        return stateGrowthPairsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu_cost_stat.QueryFourResponse)
    }

    // @@protoc_insertion_point(class_scope:edu_cost_stat.QueryFourResponse)
    private static final edu_cost_stat.Query4.QueryFourResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu_cost_stat.Query4.QueryFourResponse();
    }

    public static edu_cost_stat.Query4.QueryFourResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryFourResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryFourResponse>() {
      @java.lang.Override
      public QueryFourResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QueryFourResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryFourResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu_cost_stat.Query4.QueryFourResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cost_stat_QueryFourRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_cost_stat_QueryFourRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cost_stat_QueryFourResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_cost_stat_QueryFourResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014query4.proto\022\redu_cost_stat\"M\n\020QueryFo" +
      "urRequest\022\r\n\005years\030\001 \003(\005\022\014\n\004year\030\002 \001(\005\022\014" +
      "\n\004type\030\003 \001(\t\022\016\n\006length\030\004 \001(\t\"\230\001\n\021QueryFo" +
      "urResponse\022L\n\022state_growth_pairs\030\001 \003(\01320" +
      ".edu_cost_stat.QueryFourResponse.StateGr" +
      "owthPair\0325\n\017StateGrowthPair\022\r\n\005state\030\001 \001" +
      "(\t\022\023\n\013growth_rate\030\002 \001(\0012}\n\024EduCostStatQu" +
      "eryFour\022e\n queryTop5HighestGrowthRateSta" +
      "tes\022\037.edu_cost_stat.QueryFourRequest\032 .e" +
      "du_cost_stat.QueryFourResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_edu_cost_stat_QueryFourRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_cost_stat_QueryFourRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_cost_stat_QueryFourRequest_descriptor,
        new java.lang.String[] { "Years", "Year", "Type", "Length", });
    internal_static_edu_cost_stat_QueryFourResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_edu_cost_stat_QueryFourResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_cost_stat_QueryFourResponse_descriptor,
        new java.lang.String[] { "StateGrowthPairs", });
    internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_descriptor =
      internal_static_edu_cost_stat_QueryFourResponse_descriptor.getNestedTypes().get(0);
    internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_cost_stat_QueryFourResponse_StateGrowthPair_descriptor,
        new java.lang.String[] { "State", "GrowthRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
