// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query3.proto

package edu_cost_stat;

public final class Query3 {
  private Query3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryThreeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu_cost_stat.QueryThreeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 year = 1;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string length = 3;</code>
     * @return The length.
     */
    java.lang.String getLength();
    /**
     * <code>string length = 3;</code>
     * @return The bytes for length.
     */
    com.google.protobuf.ByteString
        getLengthBytes();
  }
  /**
   * Protobuf type {@code edu_cost_stat.QueryThreeRequest}
   */
  public static final class QueryThreeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu_cost_stat.QueryThreeRequest)
      QueryThreeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryThreeRequest.newBuilder() to construct.
    private QueryThreeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryThreeRequest() {
      type_ = "";
      length_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryThreeRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu_cost_stat.Query3.QueryThreeRequest.class, edu_cost_stat.Query3.QueryThreeRequest.Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_ = 0;
    /**
     * <code>int32 year = 1;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object length_ = "";
    /**
     * <code>string length = 3;</code>
     * @return The length.
     */
    @java.lang.Override
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <code>string length = 3;</code>
     * @return The bytes for length.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (year_ != 0) {
        output.writeInt32(1, year_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(length_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, length_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, year_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(length_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu_cost_stat.Query3.QueryThreeRequest)) {
        return super.equals(obj);
      }
      edu_cost_stat.Query3.QueryThreeRequest other = (edu_cost_stat.Query3.QueryThreeRequest) obj;

      if (getYear()
          != other.getYear()) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getLength()
          .equals(other.getLength())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query3.QueryThreeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu_cost_stat.Query3.QueryThreeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu_cost_stat.QueryThreeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu_cost_stat.QueryThreeRequest)
        edu_cost_stat.Query3.QueryThreeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu_cost_stat.Query3.QueryThreeRequest.class, edu_cost_stat.Query3.QueryThreeRequest.Builder.class);
      }

      // Construct using edu_cost_stat.Query3.QueryThreeRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        year_ = 0;
        type_ = "";
        length_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeRequest_descriptor;
      }

      @java.lang.Override
      public edu_cost_stat.Query3.QueryThreeRequest getDefaultInstanceForType() {
        return edu_cost_stat.Query3.QueryThreeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public edu_cost_stat.Query3.QueryThreeRequest build() {
        edu_cost_stat.Query3.QueryThreeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu_cost_stat.Query3.QueryThreeRequest buildPartial() {
        edu_cost_stat.Query3.QueryThreeRequest result = new edu_cost_stat.Query3.QueryThreeRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(edu_cost_stat.Query3.QueryThreeRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.year_ = year_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.length_ = length_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu_cost_stat.Query3.QueryThreeRequest) {
          return mergeFrom((edu_cost_stat.Query3.QueryThreeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu_cost_stat.Query3.QueryThreeRequest other) {
        if (other == edu_cost_stat.Query3.QueryThreeRequest.getDefaultInstance()) return this;
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                year_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                length_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int year_ ;
      /**
       * <code>int32 year = 1;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 1;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {

        year_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000001);
        year_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 2;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>string length = 3;</code>
       * @return The length.
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       * @return The bytes for length.
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string length = 3;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        length_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        length_ = getDefaultInstance().getLength();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string length = 3;</code>
       * @param value The bytes for length to set.
       * @return This builder for chaining.
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        length_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu_cost_stat.QueryThreeRequest)
    }

    // @@protoc_insertion_point(class_scope:edu_cost_stat.QueryThreeRequest)
    private static final edu_cost_stat.Query3.QueryThreeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu_cost_stat.Query3.QueryThreeRequest();
    }

    public static edu_cost_stat.Query3.QueryThreeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryThreeRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryThreeRequest>() {
      @java.lang.Override
      public QueryThreeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QueryThreeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryThreeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu_cost_stat.Query3.QueryThreeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryThreeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu_cost_stat.QueryThreeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    java.util.List<edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair> 
        getStateExpensePairsList();
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair getStateExpensePairs(int index);
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    int getStateExpensePairsCount();
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    java.util.List<? extends edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder> 
        getStateExpensePairsOrBuilderList();
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder getStateExpensePairsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code edu_cost_stat.QueryThreeResponse}
   */
  public static final class QueryThreeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu_cost_stat.QueryThreeResponse)
      QueryThreeResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryThreeResponse.newBuilder() to construct.
    private QueryThreeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryThreeResponse() {
      stateExpensePairs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryThreeResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu_cost_stat.Query3.QueryThreeResponse.class, edu_cost_stat.Query3.QueryThreeResponse.Builder.class);
    }

    public interface StateExpensePairOrBuilder extends
        // @@protoc_insertion_point(interface_extends:edu_cost_stat.QueryThreeResponse.StateExpensePair)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string state = 1;</code>
       * @return The state.
       */
      java.lang.String getState();
      /**
       * <code>string state = 1;</code>
       * @return The bytes for state.
       */
      com.google.protobuf.ByteString
          getStateBytes();

      /**
       * <code>double expense = 2;</code>
       * @return The expense.
       */
      double getExpense();
    }
    /**
     * Protobuf type {@code edu_cost_stat.QueryThreeResponse.StateExpensePair}
     */
    public static final class StateExpensePair extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:edu_cost_stat.QueryThreeResponse.StateExpensePair)
        StateExpensePairOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use StateExpensePair.newBuilder() to construct.
      private StateExpensePair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private StateExpensePair() {
        state_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new StateExpensePair();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.class, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder.class);
      }

      public static final int STATE_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object state_ = "";
      /**
       * <code>string state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        }
      }
      /**
       * <code>string state = 1;</code>
       * @return The bytes for state.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EXPENSE_FIELD_NUMBER = 2;
      private double expense_ = 0D;
      /**
       * <code>double expense = 2;</code>
       * @return The expense.
       */
      @java.lang.Override
      public double getExpense() {
        return expense_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, state_);
        }
        if (java.lang.Double.doubleToRawLongBits(expense_) != 0) {
          output.writeDouble(2, expense_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, state_);
        }
        if (java.lang.Double.doubleToRawLongBits(expense_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, expense_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair)) {
          return super.equals(obj);
        }
        edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair other = (edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair) obj;

        if (!getState()
            .equals(other.getState())) return false;
        if (java.lang.Double.doubleToLongBits(getExpense())
            != java.lang.Double.doubleToLongBits(
                other.getExpense())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
        hash = (37 * hash) + EXPENSE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getExpense()));
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code edu_cost_stat.QueryThreeResponse.StateExpensePair}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:edu_cost_stat.QueryThreeResponse.StateExpensePair)
          edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.class, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder.class);
        }

        // Construct using edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          state_ = "";
          expense_ = 0D;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_descriptor;
        }

        @java.lang.Override
        public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair getDefaultInstanceForType() {
          return edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.getDefaultInstance();
        }

        @java.lang.Override
        public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair build() {
          edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair buildPartial() {
          edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair result = new edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.state_ = state_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.expense_ = expense_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair) {
            return mergeFrom((edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair other) {
          if (other == edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.getDefaultInstance()) return this;
          if (!other.getState().isEmpty()) {
            state_ = other.state_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.getExpense() != 0D) {
            setExpense(other.getExpense());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  state_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 17: {
                  expense_ = input.readDouble();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 17
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object state_ = "";
        /**
         * <code>string state = 1;</code>
         * @return The state.
         */
        public java.lang.String getState() {
          java.lang.Object ref = state_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            state_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string state = 1;</code>
         * @return The bytes for state.
         */
        public com.google.protobuf.ByteString
            getStateBytes() {
          java.lang.Object ref = state_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            state_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string state = 1;</code>
         * @param value The state to set.
         * @return This builder for chaining.
         */
        public Builder setState(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          state_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string state = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearState() {
          state_ = getDefaultInstance().getState();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string state = 1;</code>
         * @param value The bytes for state to set.
         * @return This builder for chaining.
         */
        public Builder setStateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          state_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private double expense_ ;
        /**
         * <code>double expense = 2;</code>
         * @return The expense.
         */
        @java.lang.Override
        public double getExpense() {
          return expense_;
        }
        /**
         * <code>double expense = 2;</code>
         * @param value The expense to set.
         * @return This builder for chaining.
         */
        public Builder setExpense(double value) {

          expense_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>double expense = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearExpense() {
          bitField0_ = (bitField0_ & ~0x00000002);
          expense_ = 0D;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:edu_cost_stat.QueryThreeResponse.StateExpensePair)
      }

      // @@protoc_insertion_point(class_scope:edu_cost_stat.QueryThreeResponse.StateExpensePair)
      private static final edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair();
      }

      public static edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<StateExpensePair>
          PARSER = new com.google.protobuf.AbstractParser<StateExpensePair>() {
        @java.lang.Override
        public StateExpensePair parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<StateExpensePair> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<StateExpensePair> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int STATE_EXPENSE_PAIRS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair> stateExpensePairs_;
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair> getStateExpensePairsList() {
      return stateExpensePairs_;
    }
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder> 
        getStateExpensePairsOrBuilderList() {
      return stateExpensePairs_;
    }
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    @java.lang.Override
    public int getStateExpensePairsCount() {
      return stateExpensePairs_.size();
    }
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    @java.lang.Override
    public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair getStateExpensePairs(int index) {
      return stateExpensePairs_.get(index);
    }
    /**
     * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
     */
    @java.lang.Override
    public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder getStateExpensePairsOrBuilder(
        int index) {
      return stateExpensePairs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < stateExpensePairs_.size(); i++) {
        output.writeMessage(1, stateExpensePairs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < stateExpensePairs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stateExpensePairs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu_cost_stat.Query3.QueryThreeResponse)) {
        return super.equals(obj);
      }
      edu_cost_stat.Query3.QueryThreeResponse other = (edu_cost_stat.Query3.QueryThreeResponse) obj;

      if (!getStateExpensePairsList()
          .equals(other.getStateExpensePairsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStateExpensePairsCount() > 0) {
        hash = (37 * hash) + STATE_EXPENSE_PAIRS_FIELD_NUMBER;
        hash = (53 * hash) + getStateExpensePairsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu_cost_stat.Query3.QueryThreeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu_cost_stat.Query3.QueryThreeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu_cost_stat.QueryThreeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu_cost_stat.QueryThreeResponse)
        edu_cost_stat.Query3.QueryThreeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu_cost_stat.Query3.QueryThreeResponse.class, edu_cost_stat.Query3.QueryThreeResponse.Builder.class);
      }

      // Construct using edu_cost_stat.Query3.QueryThreeResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (stateExpensePairsBuilder_ == null) {
          stateExpensePairs_ = java.util.Collections.emptyList();
        } else {
          stateExpensePairs_ = null;
          stateExpensePairsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu_cost_stat.Query3.internal_static_edu_cost_stat_QueryThreeResponse_descriptor;
      }

      @java.lang.Override
      public edu_cost_stat.Query3.QueryThreeResponse getDefaultInstanceForType() {
        return edu_cost_stat.Query3.QueryThreeResponse.getDefaultInstance();
      }

      @java.lang.Override
      public edu_cost_stat.Query3.QueryThreeResponse build() {
        edu_cost_stat.Query3.QueryThreeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu_cost_stat.Query3.QueryThreeResponse buildPartial() {
        edu_cost_stat.Query3.QueryThreeResponse result = new edu_cost_stat.Query3.QueryThreeResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(edu_cost_stat.Query3.QueryThreeResponse result) {
        if (stateExpensePairsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            stateExpensePairs_ = java.util.Collections.unmodifiableList(stateExpensePairs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stateExpensePairs_ = stateExpensePairs_;
        } else {
          result.stateExpensePairs_ = stateExpensePairsBuilder_.build();
        }
      }

      private void buildPartial0(edu_cost_stat.Query3.QueryThreeResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu_cost_stat.Query3.QueryThreeResponse) {
          return mergeFrom((edu_cost_stat.Query3.QueryThreeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu_cost_stat.Query3.QueryThreeResponse other) {
        if (other == edu_cost_stat.Query3.QueryThreeResponse.getDefaultInstance()) return this;
        if (stateExpensePairsBuilder_ == null) {
          if (!other.stateExpensePairs_.isEmpty()) {
            if (stateExpensePairs_.isEmpty()) {
              stateExpensePairs_ = other.stateExpensePairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStateExpensePairsIsMutable();
              stateExpensePairs_.addAll(other.stateExpensePairs_);
            }
            onChanged();
          }
        } else {
          if (!other.stateExpensePairs_.isEmpty()) {
            if (stateExpensePairsBuilder_.isEmpty()) {
              stateExpensePairsBuilder_.dispose();
              stateExpensePairsBuilder_ = null;
              stateExpensePairs_ = other.stateExpensePairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stateExpensePairsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStateExpensePairsFieldBuilder() : null;
            } else {
              stateExpensePairsBuilder_.addAllMessages(other.stateExpensePairs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair m =
                    input.readMessage(
                        edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.parser(),
                        extensionRegistry);
                if (stateExpensePairsBuilder_ == null) {
                  ensureStateExpensePairsIsMutable();
                  stateExpensePairs_.add(m);
                } else {
                  stateExpensePairsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair> stateExpensePairs_ =
        java.util.Collections.emptyList();
      private void ensureStateExpensePairsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          stateExpensePairs_ = new java.util.ArrayList<edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair>(stateExpensePairs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder> stateExpensePairsBuilder_;

      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public java.util.List<edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair> getStateExpensePairsList() {
        if (stateExpensePairsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stateExpensePairs_);
        } else {
          return stateExpensePairsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public int getStateExpensePairsCount() {
        if (stateExpensePairsBuilder_ == null) {
          return stateExpensePairs_.size();
        } else {
          return stateExpensePairsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair getStateExpensePairs(int index) {
        if (stateExpensePairsBuilder_ == null) {
          return stateExpensePairs_.get(index);
        } else {
          return stateExpensePairsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder setStateExpensePairs(
          int index, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair value) {
        if (stateExpensePairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStateExpensePairsIsMutable();
          stateExpensePairs_.set(index, value);
          onChanged();
        } else {
          stateExpensePairsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder setStateExpensePairs(
          int index, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder builderForValue) {
        if (stateExpensePairsBuilder_ == null) {
          ensureStateExpensePairsIsMutable();
          stateExpensePairs_.set(index, builderForValue.build());
          onChanged();
        } else {
          stateExpensePairsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder addStateExpensePairs(edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair value) {
        if (stateExpensePairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStateExpensePairsIsMutable();
          stateExpensePairs_.add(value);
          onChanged();
        } else {
          stateExpensePairsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder addStateExpensePairs(
          int index, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair value) {
        if (stateExpensePairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStateExpensePairsIsMutable();
          stateExpensePairs_.add(index, value);
          onChanged();
        } else {
          stateExpensePairsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder addStateExpensePairs(
          edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder builderForValue) {
        if (stateExpensePairsBuilder_ == null) {
          ensureStateExpensePairsIsMutable();
          stateExpensePairs_.add(builderForValue.build());
          onChanged();
        } else {
          stateExpensePairsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder addStateExpensePairs(
          int index, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder builderForValue) {
        if (stateExpensePairsBuilder_ == null) {
          ensureStateExpensePairsIsMutable();
          stateExpensePairs_.add(index, builderForValue.build());
          onChanged();
        } else {
          stateExpensePairsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder addAllStateExpensePairs(
          java.lang.Iterable<? extends edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair> values) {
        if (stateExpensePairsBuilder_ == null) {
          ensureStateExpensePairsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, stateExpensePairs_);
          onChanged();
        } else {
          stateExpensePairsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder clearStateExpensePairs() {
        if (stateExpensePairsBuilder_ == null) {
          stateExpensePairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stateExpensePairsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public Builder removeStateExpensePairs(int index) {
        if (stateExpensePairsBuilder_ == null) {
          ensureStateExpensePairsIsMutable();
          stateExpensePairs_.remove(index);
          onChanged();
        } else {
          stateExpensePairsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder getStateExpensePairsBuilder(
          int index) {
        return getStateExpensePairsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder getStateExpensePairsOrBuilder(
          int index) {
        if (stateExpensePairsBuilder_ == null) {
          return stateExpensePairs_.get(index);  } else {
          return stateExpensePairsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public java.util.List<? extends edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder> 
           getStateExpensePairsOrBuilderList() {
        if (stateExpensePairsBuilder_ != null) {
          return stateExpensePairsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stateExpensePairs_);
        }
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder addStateExpensePairsBuilder() {
        return getStateExpensePairsFieldBuilder().addBuilder(
            edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.getDefaultInstance());
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder addStateExpensePairsBuilder(
          int index) {
        return getStateExpensePairsFieldBuilder().addBuilder(
            index, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.getDefaultInstance());
      }
      /**
       * <code>repeated .edu_cost_stat.QueryThreeResponse.StateExpensePair state_expense_pairs = 1;</code>
       */
      public java.util.List<edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder> 
           getStateExpensePairsBuilderList() {
        return getStateExpensePairsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder> 
          getStateExpensePairsFieldBuilder() {
        if (stateExpensePairsBuilder_ == null) {
          stateExpensePairsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePair.Builder, edu_cost_stat.Query3.QueryThreeResponse.StateExpensePairOrBuilder>(
                  stateExpensePairs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          stateExpensePairs_ = null;
        }
        return stateExpensePairsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu_cost_stat.QueryThreeResponse)
    }

    // @@protoc_insertion_point(class_scope:edu_cost_stat.QueryThreeResponse)
    private static final edu_cost_stat.Query3.QueryThreeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu_cost_stat.Query3.QueryThreeResponse();
    }

    public static edu_cost_stat.Query3.QueryThreeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryThreeResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryThreeResponse>() {
      @java.lang.Override
      public QueryThreeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QueryThreeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryThreeResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu_cost_stat.Query3.QueryThreeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cost_stat_QueryThreeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_cost_stat_QueryThreeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cost_stat_QueryThreeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_cost_stat_QueryThreeResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014query3.proto\022\redu_cost_stat\"?\n\021QueryTh" +
      "reeRequest\022\014\n\004year\030\001 \001(\005\022\014\n\004type\030\002 \001(\t\022\016" +
      "\n\006length\030\003 \001(\t\"\231\001\n\022QueryThreeResponse\022O\n" +
      "\023state_expense_pairs\030\001 \003(\01322.edu_cost_st" +
      "at.QueryThreeResponse.StateExpensePair\0322" +
      "\n\020StateExpensePair\022\r\n\005state\030\001 \001(\t\022\017\n\007exp" +
      "ense\030\002 \001(\0012s\n\025EduCostStatQueryThree\022Z\n\023q" +
      "ueryEconomicStates\022 .edu_cost_stat.Query" +
      "ThreeRequest\032!.edu_cost_stat.QueryThreeR" +
      "esponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_edu_cost_stat_QueryThreeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_cost_stat_QueryThreeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_cost_stat_QueryThreeRequest_descriptor,
        new java.lang.String[] { "Year", "Type", "Length", });
    internal_static_edu_cost_stat_QueryThreeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_edu_cost_stat_QueryThreeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_cost_stat_QueryThreeResponse_descriptor,
        new java.lang.String[] { "StateExpensePairs", });
    internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_descriptor =
      internal_static_edu_cost_stat_QueryThreeResponse_descriptor.getNestedTypes().get(0);
    internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_cost_stat_QueryThreeResponse_StateExpensePair_descriptor,
        new java.lang.String[] { "State", "Expense", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
